version: '3'
services:
  api:
    image: killmesoonbaby044/fastapi
    depends_on:
      - postgres
    ports:
      - "80:8000"

    env_file:
      - ./.env

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
